project:
  type: website

website:
  title: "Adarsh's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022/blog-Adarsh098
format:
  html:
    theme: theme.scss


